---
chain_id: testnet-2.0
company_name: CSA
dcld_version: 1.4.4
cosmovisor_version: 1.5.0-0.dev.3
# if defined forces moniker index for all node types
# Note. fails in case multiple nodes of the same type are deployed
moniker_index:

dcl_home: /var/lib/dcl/.dcl
dcld:
  version: "{{ dcld_version }}"
  path: "{{ dcl_home }}/cosmovisor/genesis/bin/dcld"
cosmovisor:
  version: "{{ cosmovisor_version }}"
  user: cosmovisor
  group: dcl
  path: /usr/bin/cosmovisor
  log_path: /var/log/cosmovisor/cosmovisor.log
  home: "{{ dcl_home | dirname }}"

dcld_checksums:
  # TODO upgrade the version from development to release after release
  1.5.0-0.dev.3: bf2f800ebf1f92ee44392da702f54879b611df65d72921351e26d3fa4df0ab47
  1.5.0-0.dev.2: e81461c42a462c84ad58485f665692f20a0d545afd5556880f03c12a8bbc6dad
  1.4.5: 61c164a1d6a5376c486bb92bd9dc66f90445079e18434a5ce8ecece7e6e6e406
  1.4.4: e4031c6a77aa8e58add391be671a334613271bcf6e7f11d23b04a0881ece6958
  0.12.0: ac8dc75bcbebda04fbef644ddbcee4b852d721a3522ccf06ff5d1bb8464949c6
  0.11.0: 33986b277be76d3e7b5443a09232d87d58324ad7cb6123f3d550149f2dc28452
  0.10.0: ea0e16eed3cc30b5a7f17299aca01b5d827b9a04576662d957af02608bca0fb6
  0.9.0: c333d828a124e527dd7a9c0170f77d61ad07091d9f6cd61dd0175a36b55aadce
  0.8.0: eae8e20cbe7c9fc1e090aa8ab358afdf2044636911d75c2284f733e33f0acaab
  0.7.0: 50708d4f7e00da347d4e678bf26780cd424232461c4bb414f72391c75e39545a
  0.6.0: 1ab6b9084fc0444858307f13b708d9f275d548dd2cfb3bc7d8e10d59897d7278
cosmovisor_checksums:
  1.5.0-0.dev.3: 21bff17f214e0bb0c078e7238b1ea5895388207faa6c6586a0f454097a54eb33
  1.5.0-0.dev.2: 1dbed08364bb9b767d1a88523f68ddc5a9f75b0a088ac8776fa5cf73a21f2067
  1.4.5: 30e3d9c9e680288df0cb5ed4357e40b8fb5a0108b0f57e417b283a2926e00e5c
  1.4.4: 6cb7eef58485a940bee7a98af03d1b1162b6b45448d871024b4cde314984a05f
  0.12.0: eae97a7207b5747dca9614e7b7ec478a4cc559669ad716b142dd5a2bc2266881
  0.11.0: 05bf568e34a7c92a61f268401a9f1d6df3c3f015e884a239da5d35c299da6adb
  0.10.0: 6dac8f0e0267bd930be91c6f3369eb9c35a649546ea071b223a7c8c00203d26a
  0.9.0: c05705efe5369b9d83e65ef7b252bd7c610eec414ae3f6c08681bcf49dc38e6d
  0.8.0: c05705efe5369b9d83e65ef7b252bd7c610eec414ae3f6c08681bcf49dc38e6d

dcld_download_url: "https://github.com/zigbee-alliance/distributed-compliance-ledger/releases/download/v{{ dcld.version }}/dcld"
dcld_binary_checksum: "sha256:{{ dcld_checksums[dcld.version] }}"
cosmovisor_download_url: "https://github.com/zigbee-alliance/distributed-compliance-ledger/releases/download/v{{ cosmovisor.version }}/cosmovisor"
cosmovisor_binary_checksum: "sha256:{{ cosmovisor_checksums[cosmovisor.version] }}"
